CREATE TABLE IF NOT EXISTS public.meeting_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
  session_number INTEGER NOT NULL,
  start_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_at TIMESTAMP WITHOUT TIME ZONE,
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
  cancellation_reason VARCHAR(255),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meeting_session_number UNIQUE (meeting_id, session_number),
  CONSTRAINT uq_meeting_session_start_at UNIQUE (meeting_id, start_at),
  CONSTRAINT ck_meeting_sessions_status CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  CONSTRAINT ck_meeting_sessions_time_range CHECK (end_at IS NULL OR end_at > start_at)
);

CREATE INDEX IF NOT EXISTS ix_meeting_sessions_meeting_id
  ON public.meeting_sessions(meeting_id);

CREATE INDEX IF NOT EXISTS ix_meeting_sessions_start_at
  ON public.meeting_sessions(start_at);

INSERT INTO public.meeting_sessions (
  meeting_id,
  session_number,
  start_at,
  end_at,
  status,
  created_at,
  updated_at
)
SELECT
  m.id,
  1,
  m.start_at,
  m.end_at,
  CASE
    WHEN m.status = 'closed' THEN 'completed'
    WHEN m.status = 'cancelled' THEN 'cancelled'
    ELSE 'scheduled'
  END,
  COALESCE(m.created_at, NOW()),
  COALESCE(m.updated_at, NOW())
FROM public.meetings m
WHERE m.start_at IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.meeting_sessions ms
    WHERE ms.meeting_id = m.id
      AND (
        ms.session_number = 1
        OR ms.start_at = m.start_at
      )
  );
