CREATE TABLE IF NOT EXISTS public.attendance_checkin_windows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_session_id INTEGER NOT NULL
    REFERENCES public.meeting_sessions(id) ON DELETE CASCADE,
  created_by INTEGER NOT NULL REFERENCES public.users(id),
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  opens_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  closes_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_attendance_checkin_window_time
    CHECK (closes_at > opens_at)
);

CREATE INDEX IF NOT EXISTS ix_attendance_checkin_windows_session
  ON public.attendance_checkin_windows(meeting_session_id);

CREATE INDEX IF NOT EXISTS ix_attendance_checkin_windows_token_hash
  ON public.attendance_checkin_windows(token_hash);
