CREATE TABLE IF NOT EXISTS public.meeting_views (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL
    REFERENCES public.meetings(id) ON DELETE CASCADE,
  viewer_key VARCHAR(64) NOT NULL,
  viewed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meeting_view_viewer UNIQUE (meeting_id, viewer_key)
);

CREATE INDEX IF NOT EXISTS ix_meeting_views_meeting_id
  ON public.meeting_views(meeting_id);

CREATE INDEX IF NOT EXISTS ix_meeting_views_viewed_at
  ON public.meeting_views(viewed_at);

ALTER TABLE public.meeting_views ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.meeting_views FROM anon, authenticated;
