import { apiClient } from "./client";

export const adminApi = {
  users: () => apiClient.get(`/admin/users?_=${Date.now()}`).then((res) => res.data),
  userDetail: (userId) => apiClient.get(`/admin/users/${userId}?_=${Date.now()}`).then((res) => res.data),
  meetings: () => apiClient.get(`/admin/meetings?_=${Date.now()}`).then((res) => res.data),
  meetingDetail: (meetingId) => apiClient.get(`/admin/meetings/${meetingId}?_=${Date.now()}`).then((res) => res.data),
  reports: () => apiClient.get(`/admin/reports?_=${Date.now()}`).then((res) => res.data),
  reportDetail: (reportId) => apiClient.get(`/admin/reports/${reportId}?_=${Date.now()}`).then((res) => res.data),
  updateReport: (reportId, data) => apiClient.patch(`/admin/reports/${reportId}`, data).then((res) => res.data),
  deleteMeeting: (meetingId) => apiClient.delete(`/admin/meetings/${meetingId}`).then((res) => res.data),
  restoreMeeting: (meetingId) => apiClient.post(`/admin/meetings/${meetingId}/restore`).then((res) => res.data),
  kickMember: (meetingId, userId) => apiClient.delete(`/admin/meetings/${meetingId}/members/${userId}`).then((res) => res.data),
  updateMeeting: (meetingId, data) => apiClient.patch(`/admin/meetings/${meetingId}`, data).then((res) => res.data),
  updateUser: (userId, data) => apiClient.patch(`/admin/users/${userId}`, data).then((res) => res.data),
  getSettings: () => apiClient.get(`/admin/settings?_=${Date.now()}`).then((res) => res.data),
  updateSettings: (data) => apiClient.post("/admin/settings", data).then((res) => res.data),
  getSettingsLogs: () => apiClient.get(`/admin/settings/logs?_=${Date.now()}`).then((res) => res.data),
  getSettingsDefaults: () => apiClient.get(`/admin/settings/defaults?_=${Date.now()}`).then((res) => res.data),
  updateSettingsDefaults: (data) => apiClient.post("/admin/settings/defaults", data).then((res) => res.data),
  sendMessage: (userId, message) => apiClient.post(`/admin/users/${userId}/message`, { message }).then((res) => res.data),
  sendBroadcast: (data) => apiClient.post("/admin/broadcast", data).then((res) => res.data),
  getBroadcastLogs: () => apiClient.get(`/admin/broadcast/logs?_=${Date.now()}`).then((res) => res.data),
  getAuditLogs: () => apiClient.get(`/admin/audit-logs?_=${Date.now()}`).then((res) => res.data),
  supportInquiries: (params = {}) => apiClient.get(`/admin/support/inquiries?_=${Date.now()}`, { params }).then((res) => res.data),
  updateSupportInquiry: (inquiryId, data) => apiClient.patch(`/admin/support/inquiries/${inquiryId}`, data).then((res) => res.data),
  getNotices: () => apiClient.get(`/admin/notices?_=${Date.now()}`).then((res) => res.data),
  createNotice: (data) => apiClient.post("/admin/notices", data).then((res) => res.data),
  updateNotice: (noticeId, data) => apiClient.put(`/admin/notices/${noticeId}`, data).then((res) => res.data),
  deleteNotice: (noticeId) => apiClient.delete(`/admin/notices/${noticeId}`).then((res) => res.data)
};
